Repository cjolowicz/retrocookie, pull requests merged in 2020-12, with the labels that each got.

#176 Use only string values from the cookiecutter context
  src/retrocookie/core.py
  src/retrocookie/filter.py
  tests/test_core.py
  tests/test_filter.py
Labels: bug

#185 Bump cookiecutter-hypermodern-python to 2020.11.15
  .cookiecutter.json
  .flake8
  .github/dependabot.yml
  .github/labels.yml
  .github/requirements.txt
  .github/workflows/constraints.txt
  .github/workflows/labeler.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  README.rst
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  docs/usage.rst
  mypy.ini
  noxfile.py
  poetry.lock
  pyproject.toml
  src/retrocookie/__main__.py
  src/retrocookie/git.py
  tests/conftest.py
  tests/test_core.py
Labels: dependencies

#184 Respect init.defaultBranch setting in git
  src/retrocookie/__main__.py
  src/retrocookie/core.py
  src/retrocookie/git.py
  tests/test_core.py
  tests/test_git.py
Labels: bug

#194 Add example to README.rst
  README.rst
Labels: documentation

#195 Add note about .cookiecutter.json to README.rst
  README.rst
Labels: documentation

#100 Use git-cherry-pick instead of pygit2
  src/retrocookie/core.py
  src/retrocookie/git.py
  tests/test_git.py
Labels: bug

#199 Minor cleanups in tests
  tests/test_core.py
  tests/test_filter.py
Labels: refactoring
